Links providers->sites Updated gensites and coaster-service scripts from 0.93
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/trunk@5472 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/bin/start-coaster-service b/bin/start-coaster-service
--- a/bin/start-coaster-service
+++ b/bin/start-coaster-service
@@ -11,45 +11,77 @@ crash()
 # Start futuregrid workers
 start-workers-futuregrid()
 {
+   # Setup environment
    PORT=$1
    EXECUTION_URL=http://localhost:$PORT
+   export EC2_ACCESS_KEY=$FUTUREGRID_IAAS_ACCESS_KEY
+   export EC2_SECRET_KEY=$FUTUREGRID_IAAS_SECRET_KEY
 
-   if [ ! -d "$SWIFTVMBOOT_DIR" ] || [ ! -x "$SWIFTVMBOOT_DIR/bin/bootit.sh" ]; then
+   # Check that SWIFTVMBOOT_DIR looks ok
+   if [ ! -d "$SWIFTVMBOOT_DIR" ] || [ ! -x "$SWIFTVMBOOT_DIR/futuregrid/bin/bootit.sh" ]; then
       crash "SWIFTVMBOOT_DIR incorrectly defined in coaster-service.conf"
    fi
 
-   echo Starting virtual machines.. please wait
-   $SWIFTVMBOOT_DIR/bin/bootit.sh | tee -a bootit.log
-   SWIFTVMBOOT_OUTPUT=$SWIFTVMBOOT_DIR/output.json
+   # Install ve
+   if [ ! -d "$SWIFTVMBOOT_DIR/futuregrid/ve" ]; then
+      echo Setting up environment
+      python $SWIFTVMBOOT_DIR/futuregrid/bin/virtualenv.py $SWIFTVMBOOT_DIR/futuregrid/ve
+      if [ $? -ne 0 ]; then
+         echo "Failed to created the needed python virtual environment"
+         exit 1
+      fi
+   fi
 
+   # Install cloudinitd
+   source $SWIFTVMBOOT_DIR/futuregrid/ve/bin/activate
+   easy_install cloudinitd
+   if [ $? -ne 0 ]; then
+      echo "Failed to install cloudinitd"
+      exit 1
+   fi
+
+   # Register key
+   echo "Registering the key names in all the clouds"
+   python $SWIFTVMBOOT_DIR/futuregrid/bin/register_key.py $SWIFTVMBOOT_DIR/futuregrid/hosts.txt
+   if [ $? -ne 0 ]; then
+      echo "Failed to register the key names"
+      exit 1
+   fi
+
+   # Start virtual machines
+   echo Starting virtual machines.. please wait
+   $SWIFTVMBOOT_DIR/futuregrid/bin/bootit.sh | tee -a bootit.log
+   SWIFTVMBOOT_OUTPUT=$SWIFTVMBOOT_DIR/futuregrid/output.json
    if [ ! -f "$SWIFTVMBOOT_OUTPUT" ]; then
       crash "Error: Swift VM output file $SWIFTVMBOOT_OUTPUT does not exist!"
    fi
 
    SWIFTVM_INSTANCE=`grep "Starting up run" bootit.log |awk '{print $4}'`
-   echo $SWIFTVM_INSTANCE >> $HOME/.swift/.swiftvm_instance
-
+   echo $SWIFTVM_INSTANCE >> $HOME/.swift/.swiftvm_instances
    WORKER_HOSTS=`grep hostname $SWIFTVMBOOT_OUTPUT |awk '{print $2}'|sed 's/\"//g;s/,//g;s/null//g'`
 
    # Start worker script
    for MACHINE in $WORKER_HOSTS
    do
-      # Enable ssh tunneling if needed
+      echo $MACHINE >> $HOME/.swift/machines
+      scp $SWIFT_BIN/$WORKER $WORKER_USERNAME@$MACHINE:$WORKER_LOCATION > /dev/null 2>&1
       if [ "$SSH_TUNNELING" == "yes" ]; then
          ssh -R *:$PORT:localhost:$PORT $WORKER_USERNAME@$MACHINE sleep 999 &
          echo $! >> $PID_FILE
+         echo "Starting worker on $MACHINE"
+         ssh $WORKER_USERNAME@$MACHINE "$WORKER_LOCATION/$WORKER http://localhost:$PORT $MACHINE $LOG_DIR" &
+         echo $! >> $PID_FILE
+      else
+         echo "Starting worker on $MACHINE"
+         ssh $WORKER_USERNAME@$MACHINE "$WORKER_LOCATION/$WORKER $EXECUTION_URL $MACHINE $LOG_DIR" &
+         echo $! >> $PID_FILE
       fi
-
-      # Copy and start worker script
-      scp $SWIFT_BIN/$WORKER $WORKER_USERNAME@$MACHINE:$WORKER_LOCATION > /dev/null 2>&1
-      echo "Starting worker on $MACHINE"
-      ssh $WORKER_USERNAME@$MACHINE "$WORKER_LOCATION/$WORKER $EXECUTION_URL $MACHINE $LOG_DIR" &
-      echo $! >> $PID_FILE
+      
    done
 }
 
-# EC2 workers
-start-workers-ec2()
+# Globus Provision workers
+start-workers-gp()
 {
    PORT=$1
    EXECUTION_URL=http://localhost:$PORT
@@ -80,10 +112,13 @@ start-workers-ec2()
    WORKER_HOSTS=`$SWIFTVMBOOT_DIR/bin/gp-instance-describe $SWIFTVM_INSTANCE|sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"|awk '{print $3}'`
 
    # Start worker script
+   if [ -f "$HOME/.swift/machines" ]; then
+      rm $HOME/.swift/machines
+   fi
    for MACHINE in $WORKER_HOSTS
    do
       # Create a list of machines for other applications, if needed
-      echo $MACHINE >> $HOME/.swift/.machines
+      echo $MACHINE >> $HOME/.swift/machines
 
       # Enable ssh tunneling if needed
       if [ "$SSH_TUNNELING" == "yes" ]; then
@@ -98,6 +133,75 @@ start-workers-ec2()
       echo $! >> $PID_FILE
    done
 }
+
+# EC2 workers
+start-workers-ec2()
+{
+   PORT=$1
+   EXECUTION_URL=http://localhost:$PORT
+   if [ ! -d "$SWIFTVMBOOT_DIR" ] || [ ! -x "$SWIFTVMBOOT_DIR/ec2/bin/ec2-run-instances" ]; then
+      crash "SWIFTVMBOOT_DIR incorrectly defined in coaster-service.conf"
+   fi
+
+   export EC2_HOME="$SWIFTVMBOOT_DIR/ec2" 
+   export EC2_PRIVATE_KEY="$EC2_KEYFILE"
+   export EC2_CERT="$EC2_CERTFILE"
+
+   echo Creating instance..
+   $SWIFTVMBOOT_DIR/ec2/bin/ec2-run-instances "$EC2_AMI" -t "$EC2_INSTANCE_TYPE" -n "$EC2_NODES" -K "$EC2_KEYFILE" -C "$EC2_CERT"
+   SWIFTVM_INSTANCES=$( $SWIFTVMBOOT_DIR/ec2/bin/ec2-describe-instances | grep INSTANCE | grep -v terminated |awk '{print $2}' )
+   echo $SWIFTVM_INSTANCES >> $HOME/.swift/.swiftvm_instances
+   echo Waiting for nodes to boot..
+
+   # Wait until all instances are listed as running
+   while /bin/true
+   do
+      SWIFTVM_INSTANCES_AS_STRING=$( echo $SWIFTVM_INSTANCES | tr "\\n" " ")
+      STATUS_LIST=$( $SWIFTVMBOOT_DIR/ec2/bin/ec2-describe-instances $SWIFTVM_INSTANCES_AS_STRING | grep INSTANCE | grep -v terminated | awk '{print $6}' |sort -u )
+      if [ "$STATUS_LIST" == "running" ]; then
+         break
+      fi
+      sleep 5
+   done
+
+   # There is some delay between when the machines are 'running', and when system utilities like sshd are started
+   sleep 30
+
+   WORKER_HOSTS=$( $SWIFTVMBOOT_DIR/ec2/bin/ec2-describe-instances $SWIFTVM_INSTANCES_AS_STRING | grep INSTANCE | grep -v terminated | awk '{print $4}' )
+
+   if [ -f "$HOME/.swift/machines" ]; then
+      rm $HOME/.swift/machines
+   fi
+
+   # Start worker script
+   SSH_OPTS="-i $EC2_KEYFILE -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
+   for MACHINE in $WORKER_HOSTS
+   do
+
+      # Create a list of machines for other applications, if needed
+      echo $MACHINE >> $HOME/.swift/machines
+
+      # Copy and start worker script
+      scp $SSH_OPTS $SWIFT_BIN/$WORKER $WORKER_USERNAME@$MACHINE:$WORKER_LOCATION > /dev/null 2>&1
+      echo $! >> $PID_FILE
+
+      # Enable ssh tunneling if needed
+      if [ "$SSH_TUNNELING" == "yes" ]; then
+         ssh $SSH_OPTS -R *:$PORT:localhost:$PORT $WORKER_USERNAME@$MACHINE sleep 999 > /dev/null 2>&1 &
+         sleep 10
+         ssh $SSH_OPTS $WORKER_USERNAME@$MACHINE "$WORKER_LOCATION/$WORKER http://localhost:$PORT $MACHINE $LOG_DIR" 2>&1 &
+         echo $! >> $PID_FILE
+      else
+         echo "Starting worker on $MACHINE"
+         ssh $SSH_OPTS $WORKER_USERNAME@$MACHINE "$WORKER_LOCATION/$WORKER $EXECUTION_URL $MACHINE $LOG_DIR" > /dev/null 2>&1 &
+         echo $! >> $PID_FILE
+      fi
+
+      # Copy SSH key for easier access
+      cat $HOME/.ssh/*.pub | ssh $SSH_OPTS $WORKER_USERNAME@$MACHINE 'umask 077; cat >> $HOME/.ssh/authorized_keys' > /dev/null 2>&1
+   done
+}
+
 
 # Start SSH workers
 start-workers-ssh()
@@ -125,7 +229,7 @@ start-workers-ssh()
          ssh $WORKER_USERNAME@$WORKER_RELAY_HOST ssh $MACHINE mkdir -p $WORKER_LOCATION > /dev/null 2>&1
          ssh $WORKER_USERNAME@$WORKER_RELAY_HOST "scp /tmp/$WORKER $WORKER_USERNAME@$MACHINE:$WORKER_LOCATION" > /dev/null 2>&1
          echo Starting worker on $MACHINE
-         ssh $WORKER_USERNAME@$WORKER_RELAY_HOST ssh $WORKER_USERNAME@$MACHINE "WORKER_LOGGING_LEVEL=$WORKER_LOGGING_LEVEL $WORKER_LOCATION/$WORKER $EXECUTION_URL $MACHINE $WORKER_LOG_DIR" &
+         ssh $WORKER_USERNAME@$WORKER_RELAY_HOST ssh $WORKER_USERNAME@$MACHINE "WORKER_LOGGING_LEVEL=$WORKER_LOGGING_LEVEL $WORKER_LOCATION/$WORKER http://localhost:$PORT $MACHINE $WORKER_LOG_DIR" &
          echo $! >> $PID_FILE
       # Connect directly
       else
@@ -308,6 +412,9 @@ case $WORKER_MODE in
    futuregrid)
       start-workers-futuregrid $LOCAL_PORT
       ;;
+   gp)
+      start-workers-gp $LOCAL_PORT
+      ;;
    ec2)
       start-workers-ec2 $LOCAL_PORT
       ;;
@@ -333,7 +440,7 @@ use.provider.staging=true
 wrapperlog.always.transfer=false
 execution.retries=0
 provider.staging.pin.swiftfiles=false
-sitedir.keep=true
+sitedir.keep=false
 EOF
 fi
 
