Disable chxml script to avoid erronous error messages
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/branches/release-0.94@6042 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/bin/swift b/bin/swift
--- a/bin/swift
+++ b/bin/swift
@@ -63,11 +63,11 @@ CMDLINE=`fixCommandLine "$@"`
 
 # make sure sites.xml file is well-formed
 
-$SWIFT_HOME/bin/chxml $CMDLINE
-if [ "$?" != 0 ]; then
-	echo "Could not process input files!"
-	exit 1
-fi
+#$SWIFT_HOME/bin/chxml $CMDLINE
+#if [ "$?" != 0 ]; then
+#	echo "Could not process input files!"
+#	exit 1
+#fi
 
 ### SETUP OTHER ENV VARIABLES ####
 
