Swiftrun and nswift scripts
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/trunk@6639 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/bin/swiftrun b/bin/swiftrun
--- a/bin/swiftrun
+++ b/bin/swiftrun
@@ -1,116 +1,214 @@
-#!/bin/bash
+#!/usr/bin/perl -w
 
-# Verify an argument is not null
-verify_not_null()
-{
-   argname=$1; shift
-   if [ _$1 != _ ]; then
-      return 0;
-   else
-      echo $0: value for $argname can not be null
-      exit 1
-   fi
+use strict;
+use warnings;
+use File::Basename;
+use Getopt::Long qw(GetOptionsFromArray);
+use Switch;
+use Cwd;
+
+Getopt::Long::Configure("pass_through");
+
+my %properties = ();		# Hash storing all swift properties
+my @property_files = ();	# List of swift property files to be read
+my $option_tcfile;		# Value of -tc.file option
+my $option_sitesfile;		# Value of -sites.file option
+my $option_siteslist;		# Value of -sites option, comma separated
+my $option_config;		# Value of -config option
+my @sites;			# List of sites from -sites in array
+my $run_directory;		# Run directory to be created, run.NNNN
+my @new_swift_args;		# New command line arguments
+my @original_swift_args;	# Original arguments
+
+# List of xml shortcuts. Keep in lower case.
+my %xml_aliases = (
+                   'provider'     => 'provider.coaster',
+                   'jobspernode'  => 'globus.jobspernode',
+                   'maxwalltime'  => 'globus.maxwalltime',
+                   'queue'        => 'globus.queue',
+                   'initialscore' => 'karajan.initialscore',
+);
+
+# Verify a property file exists and add it to the search path
+sub add_property_file {
+   my $property_file = $_[0];
+   if( -e "$property_file" ) {
+      push( @property_files, $property_file );
+   }
 }
 
-# crash: Report a problem and exit
-crash()
-{
-    MSG=$1
-    echo ${MSG}  >&2
-    exit 1
+# Create a string with a single pool entry
+sub create_pool_entry {
+   my $site = $_[0];
+   my $pool = "\n<pool handle=\"" . $site . "\">\n";
+   while( my( $key, $value ) = each( %properties ) ) {
+      if( $key =~ /^\s*site.$site/ ) {
+         $pool .= &property_to_xml( $key, $value );
+      }
+   }
+   $pool .= "</pool>\n";
+   return $pool;
 }
 
-# Create .swift structure
-create_dotswift()
-{
-   if [ ! -d "$HOME/.swift" ]; then
-      mkdir $HOME/.swift || crash "Unable to mkdir $HOME/.swift"
-   fi
+# Given a string in format site.beagle.globus.jobsPerNode=12, convert to xml
+sub property_to_xml {
+   my $key = $_[0];
+   my $value = $_[1];
+   my ( $site, $sitename, $namespace, $property ) = split(/\./, $key);
 
-   if [ ! -d "$HOME/.swift/runs" ]; then
-      mkdir $HOME/.swift/runs || crash "Unable to mkdir $HOME/.swift/runs"
-   fi
+   # In the case of a shortened definition, check for aliases 
+   if ( !defined( $property ) ) {
+      if ( defined( $xml_aliases{ lc( $namespace )})) { 
+         ( $namespace, $property ) = split(/\./, $xml_aliases{ lc($namespace) });
+      }
+   }     
+   
+   # Make sure to handle special cases that are not in the namespace=x, key=y, format
+   switch($namespace) {
+      case "provider"	   { return "<execution provider=\"" . $property . "\" jobmanager=\"" . $value . "\"/>\n"; }
+      case "workdirectory" { return "<workdirectory>$value</workdirectory>\n"; }
+      case "filesystem"    { return "<filesystem provider=\"" . $value . "\"/>\n"; }
+      else                 { return "<profile namespace=\"" . $namespace . "\" key=\"" . $property . "\">" . $value . "</profile>\n"; }
+   }
+} 
 
-   if [ ! -d "$HOME/.swift/runs/current" ]; then
-      mkdir $HOME/.swift/runs/current || crash "Unable to mkdir $HOME/.swift/runs/current"
-   fi
+# Write apps to file in tc.data format
+sub write_apps {
+   my $app_filename = $_[0];
+   open( APP_FILE, ">$run_directory/$app_filename" ) || die "Unable to open $run_directory/$app_filename\n";
 
-  if [ ! -d "$HOME/.swift/runs/completed" ]; then
-     mkdir $HOME/.swift/runs/completed || crash "Unable to mkdir $HOME/.swift/runs/completed"
-  fi
+   # Find app definitions
+   while( my( $key, $value ) = each( %properties ) ) {
+      if( $key =~ /^\s*app./ ) {
+         my ( $app, $site, $command ) = split(/\./, $key);
+
+         # Handle wildcards for site names
+         if ( $site eq "*" ) { 
+            foreach my $nsite( @sites ) {
+               print APP_FILE "$nsite $command $value\n";
+            }
+         } 
+
+         # Handle apps for defined sites
+         elsif ( grep( /^$site$/, @sites ) ) {
+            print APP_FILE "$site $command $value\n";
+         }
+      }
+   }
+   # Update command line args
+   push( @new_swift_args, "-tc.file $run_directory/$app_filename" );
 }
 
-# Parse command line arguments
-args=""
-script=""
-while [ $# -gt 0 ]
-do
-   case "$1" in
-      -site|-sites|-s) SITES=$2; verify_not_null sites $SITES; shift ;;
-      -config|-c) CONFIG=$2; verify_not_null config $CONFIG; shift ;;
-      *) if [ -z "$script" ] && [[ $1 == *.swift ]]; then script="$1"
-         else args+="$1 "
-         fi ;;
-   esac
-   shift
-done
+# Write properties to file
+sub write_properties {
+   my $property_filename = $_[0];
+   open( PROPERTY_FILE, ">$run_directory/$property_filename" ) || die "Unable to open $run_directory/$property_filename\n";
+   while( my( $key, $value ) = each( %properties ) ) {
+      # Ignore properties that start with app. or site.
+      next if $key =~ /^\s*app./;
+      next if $key =~ /^\s*site./;
+      print PROPERTY_FILE "$key=$value\n";
+   }
+   push( @new_swift_args, "-config $run_directory/$property_filename" );
+}
 
-# Create run directory
-create_dotswift
-rundir=$( echo run??? | sed -e 's/^.*run//' | awk '{ printf("run%03d\n", $1+1)}' )
-mkdir $rundir
+# Write sites.xml to disk
+sub write_sites {
+   my $filename = $_[0];
+   open(SITES, ">$run_directory/$filename") || die "Unable to open $run_directory/$filename\n";
+   print SITES "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
+   print SITES "<config xmlns=\"http://www.ci.uchicago.edu/swift/SwiftSites\">\n";
 
-# Link input_files
-if [ -d "input_files" ]; then
-   for input_file in input_files/*
-   do
-      ln -s $PWD/$input_file $rundir
-   done
-fi
+   foreach my $site(@sites) {
+      print SITES &create_pool_entry($site);
+   }
 
-# Swift script
-if [ -f "$script" ]; then 
-   cp $script $rundir
-fi
+   print SITES "\n</config>\n";
+   close(SITES);
+   push(@new_swift_args, "-sites.file $run_directory/$filename");
+}
 
-# Copy config file if specified
-if [ -f "$CONFIG" ]; then
-   cp $CONFIG $rundir
-   CONFIG=$( basename $CONFIG )
-fi
+# Getopt::Long can't accept dots in arguments, work around to make things easy
+foreach my $arg(@ARGV) {
+   $arg =~ s/sites.file/sitesfile/g;
+   $arg =~ s/tc.file/tcfile/g;
+}
 
-# Create sites.xml
-IFS=","
-echo "<config>" > $rundir/sites.xml
-for site in $SITES
-do
-   # If config is not defined, but there is a config in conf/ that matches, use that
-   if [ -z "$CONFIG" ] && [ -f "conf/$site.cf" ]; then
-      cp conf/$site.cf $rundir
-      config=$site.cf
-   fi  
+# Command line arguments we care about
+@original_swift_args = @ARGV;
+GetOptionsFromArray(
+           \@original_swift_args, 
+           'sitesfile=s'     => \$option_sitesfile,
+           'tcfile=s'        => \$option_tcfile,
+           'config=s'        => \$option_config,
+           'site|sites=s'    => \$option_siteslist,
+);
 
-   if [ -f "conf/$config" ]; then
-      gensites -p conf/$config $site >> $rundir/sites.xml
-   else
-      gensites $site >> $rundir/sites.xml
-   fi
+# Set @sites array from comma separated list of sites
+if(defined($option_siteslist)) {
+   @sites = split(',', $option_siteslist);
+}
 
-done
-echo "</config>" >> $rundir/sites.xml
-mv tc.data $rundir
-cd $rundir
+# Verify Swift is found in PATH
+my $swift_etc_directory = dirname(dirname(`which swift`)) . "/etc";
+if( ! -d $swift_etc_directory ) { die "Unable to find a valid Swift installation"; }
 
-if [ -z "$CONFIG" ]; then
-   CONFIG=$config
-fi
+# Set the search order for properties
+&add_property_file("$swift_etc_directory/swift.properties");
+&add_property_file("$ENV{SWIFT_CONFIG}/swift.properties") if defined($ENV{SWIFT_CONFIG});
+&add_property_file("$ENV{HOME}/.swift/swift.properties");
+&add_property_file("swift.properties");
 
-# Run
-timestamp=$( date +%s )
-ln -s $PWD $HOME/.swift/runs/current/$rundir.$timestamp 
-if [ -n "$CONFIG" ]; then
-   eval time swift -sites.file sites.xml -tc.file tc.data -config $CONFIG $( basename $script ) $args 2>&1 | tee swift.out
-else
-   eval time swift -sites.file sites.xml -tc.file tc.data $( basename $script ) $args 2>&1 | tee swift.out
-fi
-mv $HOME/.swift/runs/current/$rundir.$timestamp $HOME/.swift/runs/completed
+# Set property values
+foreach my $property_file(@property_files) {
+   open(PROPERTIES, $property_file) || die "Unable to open $property_file";
+   while( <PROPERTIES> ) {
+      chomp;
+      next if /^\s*#/ || /^(\s)*$/; # Ignore blank lines and comments
+      my ($key, $value) = split('=', $_, 2);
+      $value =~ s/\$(\w+)/$ENV{$1}/g; # Substitute environment variables
+      $properties{ $key } = $value;
+   }
+}
+
+# Create/increment run directory
+my $run_number = 0;
+my @run_directories = <run????>;
+
+if(@run_directories) {
+   $run_number = $run_directories[-1];
+   $run_number =~ s/run//g;
+   $run_number++;
+}
+
+$run_directory = getcwd() . "/" . sprintf "run%04s", $run_number;
+mkdir($run_directory) || die "Unable to create run directory $run_directory\n";
+
+# Write swift configuration files
+&write_sites("sites.xml") if defined( $option_siteslist );
+&write_apps("tc.data")    if ( !defined( $option_tcfile ) && defined( $option_siteslist ));
+&write_properties("cf")   if !defined( $option_config );
+
+# Repair args with dots
+foreach my $arg(@ARGV) {
+   $arg =~ s/sitesfile/sites.file/g;
+   $arg =~ s/tcfile/tc.file/g;
+}
+
+# Make sure -sites isn't in the arguments we send back to swift
+while( @ARGV ) {
+   my $option = shift;
+   switch( $option ) {
+      case "-site" { shift; }
+      case "-sites" { shift; }
+      else { push( @new_swift_args, $option ); }
+   }
+}
+
+push( @new_swift_args, sprintf( "-logfile $run_directory/run%04s.log", $run_number ));
+
+foreach my $arg( @new_swift_args ) {
+   print "$arg ";
+}
+
+print "\n";
