language test was not exiting with failure code when known-bad test failed
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/trunk@1782 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/tests/language/run b/tests/language/run
--- a/tests/language/run
+++ b/tests/language/run
@@ -42,7 +42,7 @@ for a in *.swift; do
 
   echo Attempting vdlc known-bad $a
   vdlc $a
-  if [ "$?" -eq "0" ]; then echo "TEST FAILED - COMPILE SUCCEEDED"; exit; fi
+  if [ "$?" -eq "0" ]; then echo "TEST FAILED - COMPILE SUCCEEDED"; exit 2; fi
   echo ----------===========================----------
 done
 echo Finished all syntax tests
