language behaviour tests can have no output - this is for testing bug 83 which is a hang bug
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/trunk@917 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/tests/language-behaviour/run b/tests/language-behaviour/run
--- a/tests/language-behaviour/run
+++ b/tests/language-behaviour/run
@@ -17,12 +17,18 @@ for testfn in $TESTS; do
 
   for e in $EXPECTEDS; do
 
-    echo checking $e
-    out=$(basename $e .expected)
+    if [ -f $e ]; then
 
-    if [ "$?" -ne "0" ]; then echo "TEST FAILED"; exit; fi
-    diff -q ${out} ${e}
-    if [ "$?" -ne "0" ]; then echo "OUTPUT DIFFERS"; exit; fi
+      echo checking $e
+      out=$(basename $e .expected)
+
+      if [ "$?" -ne "0" ]; then echo "TEST FAILED"; exit; fi
+      diff -q ${out} ${e}
+      if [ "$?" -ne "0" ]; then echo "OUTPUT DIFFERS"; exit; fi
+
+    else
+      echo "$e does not exist"
+    fi
 
   done
 
