args validation in run-gwms-workers
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/trunk@5342 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/bin/grid/run-gwms-workers b/bin/grid/run-gwms-workers
--- a/bin/grid/run-gwms-workers
+++ b/bin/grid/run-gwms-workers
@@ -1,9 +1,16 @@
 #!/bin/bash
 
+die () {
+    echo >&2 "$@"
+    exit 1
+}
+
 workerExecutable=`which worker.pl`
 workerWrapper=`which run-worker.sh`
 workerContact=$1
 n=$2
+
+[ "$#" -eq 2 ] || die "2 arguments required, $# provided"
 
 cat > myjob.condor <<EOF
 universe = vanilla
@@ -34,4 +41,3 @@ queue $n
 EOF
 
 condor_submit myjob.condor
-
