commit snapshot of working version - work in progress
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/trunk@4956 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/bin/grid/start-ranger-service~ b/bin/grid/start-ranger-service~
--- a/bin/grid/start-ranger-service~
+++ b/bin/grid/start-ranger-service~
@@ -1,18 +1,61 @@
 #! /bin/bash
 
-# FIXME: make these commandline keyword arguments, eg --nodes=
+function usage ()
+{
+       echo "Usage:"
+       echo " $0 --nodes nnodes --walltime hh:mm:ss --project proj-name --queue q-name --user user-name"
+}
 
-NODES=${1:-1}
-WALLTIME=${2:-00:10:00}
-PROJECT=${3:-TG-DBS080004N}
-QUEUE=${4:-development}
-REMOTE_USER=${5:-tg455797}
+if [ $# -ne 10 ]
+then
+    usage
+    exit 1
+fi
+
+while test "$1" != "" ; do
+    case $1 in
+        --nodes|-n)
+                NODES="$2"
+                shift
+        ;;
+        --walltime|-t)
+                WALLTIME="$2"
+                shift
+        ;;
+        --project|-p)
+                PROJECT="$2"
+                shift
+        ;;
+        --queue|-q)
+                QUEUE="$2"
+                shift
+        ;;
+        --user|-u)
+                REMOTE_USER="$2"
+                shift
+        ;;
+        -*)
+                echo "Error: no such option $1"
+                usage
+                exit 1
+        ;;
+    esac
+    shift
+done
+
+
+
+#NODES=${1:-1}
+#WALLTIME=${2:-00:10:00}
+#PROJECT=${3:-TG-DBS080004N}
+#QUEUE=${4:-development}
+#REMOTE_USER=${5:-$USER}
 
 STARTSERVICE=true
 HOST=tg-login.ranger.tacc.teragrid.org
 BIN=$(cd $(dirname $0); pwd)
 
-echo NODES=$NODES WALLTIME=$WALLTIME PROJECT=$PROJECT REMOTE_USER=$REMOTE_USER
+echo NODES=$NODES WALLTIME=$WALLTIME PROJECT=$PROJECT REMOTE_USER=$REMOTE_USER QUEUE=$QUEUE
 LOGLEVEL=INFO # INFO, DEBUG, TRACE for increasing detail
 
 CORESPERNODE=16
@@ -39,7 +82,7 @@ if [ $STARTSERVICE = true ]; then
       <profile namespace="karajan" key="initialScore">10000</profile>
       <!-- <filesystem provider="local" url="none" /> -->
       <profile namespace="swift" key="stagingMethod">proxy</profile>
-      <workdirectory>/tmp/wilde</workdirectory>
+      <workdirectory>/tmp/$USER</workdirectory>
     </pool>
   </config>
 EOF
@@ -59,12 +102,17 @@ if [ $? != 0 ]; then
   exit 1
 fi
 
-echo Created remote dir
+echo Created remote dir: $rdir
 
 scp $BIN/{worker.pl,workers.ranger.sh,workers.ranger.sub} $REMOTE_USER@$HOST:$rdir
 
-echo Copied grid tools to remote dir
+echo Copied grid tools to remote dir: $rdir
 
-ssh $REMOTE_USER@$HOST qsub -A $PROJECT -N runworkers -pe 16way $(($NODES * 16)) -l h_rt=$WALLTIME -q $QUEUE -v SERVICE_URL=$SERVICE_URL,WORKER_LOGLEVEL=$LOGLEVEL $rdir/workers.ranger.sub
+echo Submitting ...
+
+echo "ssh $REMOTE_USER@$HOST qsub -A $PROJECT -N runworkers -pe 16way $(($NODES * 16)) -q $QUEUE -l h_rt=$WALLTIME -v SERVICE_URL=$SERVICE_URL, WORKER_LOGLEVEL=$LOGLEVEL $rdir/workers.ranger.sub"
+
+ssh $REMOTE_USER@$HOST qsub -A $PROJECT -N runworkers -pe 16way $(($NODES * 16)) -q $QUEUE -l h_rt=$WALLTIME -v SERVICE_URL=$SERVICE_URL,WORKER_LOGLEVEL=$LOGLEVEL $rdir/workers.ranger.sub
 
 echo Submitted remote worker launching script
+
