also for the normal swiftwrap
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/branches/release-0.93@5004 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/libexec/_swiftwrap b/libexec/_swiftwrap
--- a/libexec/_swiftwrap
+++ b/libexec/_swiftwrap
@@ -450,7 +450,7 @@ if [ "$KICKSTART" == "" ]; then
 		fi
 		"$EXEC" "${CMDARGS[@]}" 1>"$STDOUT" 2>"$STDERR" <"$STDIN"
 	fi
-	checkError $? "Exit code $?"
+	checkError $? "Application $EXEC failed with an exit code of $?"
 else
 	if [ ! -f "$KICKSTART" ]; then
 		log "Kickstart executable ($KICKSTART) not found"
@@ -470,7 +470,7 @@ else
 		mv -f kickstart.xml "$WFDIR/kickstart/$JOBDIR/$ID-kickstart.xml" 2>&1 >& "$INFO"
 		checkError 254 "Failed to copy Kickstart record to shared directory"
 		if [ "$APPEXIT" != "0" ]; then
-			fail $APPEXIT "Exit code $APPEXIT"
+			fail $APPEXIT "Application $EXEC failed with an exit code of $APPEXIT"
 		fi
 	fi
 fi
