Updates for ec2-provider. Build issues remain, and submit scripts require absolute paths. Added support for passing ec2 attributes as coaster jobOptions from swift.conf Cleaned up handling of configs in the job handler scripts Tested.
git-svn-id: https://svn.code.sf.net/p/cogkit/svn/trunk@4028 5b74d2a0-fa0e-0410-85ed-ffba77ec0bde

diff --git a/modules/provider-localscheduler/examples/ec2-cloud-provider/stcancel b/modules/provider-localscheduler/examples/ec2-cloud-provider/stcancel
--- a/modules/provider-localscheduler/examples/ec2-cloud-provider/stcancel
+++ b/modules/provider-localscheduler/examples/ec2-cloud-provider/stcancel
@@ -1,10 +1,33 @@
 #!/bin/bash
 
 LOG=/home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/log
-CONF=/home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/configs
+LOGGING=1 # Either 1 or 0
+log()
+{
+    [[ "$LOGGING" == "1" ]] && echo $* >> $LOG
+}
+
+JOBID=$1
+CONF=/tmp/$JOBID
+EXITCODE=0
+
+# Check for the conf file for the job at /tmp/<jobid>
+if [ ! -f "$CONF" ]
+then
+    echo "ERROR: Could not find conf script at /tmp/$1" 1>&2
+    exit -1
+fi
 
 if [[ "$1" != "" ]]
 then
-    echo "Cancelling $1" >> $LOG
-    python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --cancel $CONF --jobid $1 | tee -a $LOG
+    log "Cancelling $JOBID"
+    python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --cancel $CONF --jobid $JOBID
+    EXITCODE=$?
+    if [[ "$EXITCODE" == "0" ]]
+    then
+        log "Done cancelling $JOBID"
+        rm $CONF
+    fi
 fi
+
+exit $EXITCODE
diff --git a/modules/provider-localscheduler/examples/ec2-cloud-provider/ststat b/modules/provider-localscheduler/examples/ec2-cloud-provider/ststat
--- a/modules/provider-localscheduler/examples/ec2-cloud-provider/ststat
+++ b/modules/provider-localscheduler/examples/ec2-cloud-provider/ststat
@@ -1,11 +1,24 @@
 #!/bin/bash
 
 LOG=/home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/log
-CONF=/home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/configs
+LOGGING=1 # Either 1 or 0
+log()
+{
+    [[ "$LOGGING" == "1" ]] && echo $* >> $LOG
+}
+
+JOBID=$1
+CONF=/tmp/$JOBID
+
+# Check for the conf file for the job at /tmp/<jobid>
+if [ ! -f "$CONF" ]
+then
+    echo "ERROR: Could not find conf script at /tmp/$1" 1>&2
+    exit -1
+fi
 
 if [[ "$1" != "" ]]
 then
-	echo "Stat'ing for $1 " >> $LOG
-    echo "python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --status $CONF --jobid $1" >> $LOG
-    python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --status $CONF --jobid $1 | tee -a $LOG
+	log "Stat'ing for $1 PWD: $PWD"
+    python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --status $CONF --jobid $JOBID | tee -a $LOG
 fi
